# Generated by Django 5.2.1 on 2025-07-15 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="User's first name", max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="User's last name", max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(help_text="User's email address", max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Customer Support'), ('partnership', 'Partnership'), ('feedback', 'Feedback'), ('other', 'Other')], help_text='Message subject category', max_length=20, verbose_name='Subject')),
                ('message', models.TextField(help_text="User's message content", verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', help_text='Current status of the message', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the message was submitted', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the message was last updated', verbose_name='Updated At')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="User's IP address when message was sent", null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text="User's browser information", null=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
