# Generated by Django 5.2.1 on 2025-07-16 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User's full name", max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('phone_number', models.CharField(help_text="User's phone number", max_length=20, verbose_name='Phone Number')),
                ('message', models.TextField(blank=True, help_text='Optional message from user', null=True, verbose_name='Message')),
                ('is_email_sent', models.BooleanField(default=False, help_text='Whether welcome email has been sent', verbose_name='Email Sent')),
                ('is_in_whatsapp_channel', models.BooleanField(default=False, help_text='Whether user is added to WhatsApp channel', verbose_name='In WhatsApp Channel')),
                ('is_in_whatsapp_group', models.BooleanField(default=False, help_text='Whether user is added to WhatsApp group', verbose_name='In WhatsApp Group')),
                ('is_notified', models.BooleanField(default=False, help_text='Whether user has been notified about updates', verbose_name='Notified')),
                ('is_store', models.BooleanField(default=False, help_text='Whether user is interested in store/shop', verbose_name='Store')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the user joined waitlist', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated', verbose_name='Updated At')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="User's IP address when joined", null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text="User's browser information", null=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'db_table': 'waitlist_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
